#! /bin/sh


## Autostart

# Restore wallpaper
nitrogen --restore &

# Network manager
nm-applet &

pgrep -x sxhkd > /dev/null || sxhkd &
# bash $HOME/.screenlayout/screen.sh

# Polybar
$HOME/.config/polybar/launch.sh

# Kill if already running
# killall -9 picom sxhkd dunst xfce4-power-manager ksuperkey
killall -9 picom sxhkd dunst ksuperkey

# Launch notification daemon
dunst -config $HOME/.config/dunstrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi

# Launch keybindings daemon
sxhkd &

# Enable power management
# xfce4-power-manager &

# Start udiskie
# udiskie &

# start compositor
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom --config $HOME/.config/picom.conf &


workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' ''
		let name++
	done
}
workspaces

bspc config border_width            3
bspc config window_gap              10
bspc config split_ratio             0.50

bspc config focused_border_color    "#7aa2f7"
bspc config normal_border_color     "#32344a"
bspc config active_border_color     "#444b6a"

bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config paddingless_monocle     true
bspc config single_monocle          false
bspc config focus_follows_pointer   false


# fix pointer
xsetroot -cursor_name left_ptr

# workspace 1 (Terminals)
declare -a terminal=(Alacritty)
for i in ${terminal[@]}; do
    bspc rule -a $i desktop='^1' follow=on focus=on; done

# workspace 2 (Internet Browser)
declare -a web=(google-chrome-stable)
for i in ${web[@]}; do
    bspc rule -a $i desktop='^2' follow=on focus=on; done

# workspace 3 (Files)
declare -a filem=(Pcmanfm)
for i in ${filem[@]}; do
    bspc rule -a $i desktop='^3' follow=on focus=on; done

# workspace 4 (Text Editor)
declare -a office=(Code)
for i in ${office[@]}; do
    bspc rule -a $i desktop='^4' follow=on focus=on; done

# workspace 5 (Media)
declare -a media=(vlc obs mpv mplayer lxmusic Gimp Gimp-2.10 \
"VirtualBox Manager")
for i in ${media[@]}; do
    bspc rule -a $i desktop='^5' follow=on focus=on; done

# workspace 7 (Settings)
declare -a settings=(GParted Lxappearance Lxtask Lxrandr Arandr Pavucontrol)
for i in ${settings[@]}; do
    bspc rule -a $i desktop='^7' follow=on focus=on; done

# floating windows
declare -a floats=(Lxappearance Arandr)
for i in ${floats[@]}; do
    bspc rule -a $i state=floating follow=on focus=on; done

